/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from "@payloadcms/db-vercel-postgres"
import { relations, sql } from "@payloadcms/db-vercel-postgres/drizzle"
import {
	boolean,
	foreignKey,
	index,
	integer,
	jsonb,
	numeric,
	pgEnum,
	pgTable,
	serial,
	timestamp,
	uniqueIndex,
	varchar,
} from "@payloadcms/db-vercel-postgres/drizzle/pg-core"
export const enum_users_role = pgEnum("enum_users_role", ["admin", "editor", "viewer"])
export const enum_tokens_tags = pgEnum("enum_tokens_tags", ["streme", "testnet", "underlying", "supertoken"])
export const enum_tokens_token_type = pgEnum("enum_tokens_token_type", [
	"underlyingToken",
	"pureSuperToken",
	"nativeAssetSuperToken",
	"wrapperSuperToken",
])
export const enum_api_keys_status = pgEnum("enum_api_keys_status", ["active", "revoked"])
export const enum_push_requests_status = pgEnum("enum_push_requests_status", [
	"pending",
	"processing",
	"completed",
	"failed",
])

export const users_token_permissions_allowed_tags = pgTable(
	"users_token_permissions_allowed_tags",
	{
		_order: integer("_order").notNull(),
		_parentID: integer("_parent_id").notNull(),
		id: varchar("id").primaryKey(),
		tag: varchar("tag"),
	},
	(columns) => [
		index("users_token_permissions_allowed_tags_order_idx").on(columns._order),
		index("users_token_permissions_allowed_tags_parent_id_idx").on(columns._parentID),
		foreignKey({
			columns: [columns["_parentID"]],
			foreignColumns: [users.id],
			name: "users_token_permissions_allowed_tags_parent_id_fk",
		}).onDelete("cascade"),
	],
)

export const users_token_permissions_allowed_addresses = pgTable(
	"users_token_permissions_allowed_addresses",
	{
		_order: integer("_order").notNull(),
		_parentID: integer("_parent_id").notNull(),
		id: varchar("id").primaryKey(),
		address: varchar("address"),
	},
	(columns) => [
		index("users_token_permissions_allowed_addresses_order_idx").on(columns._order),
		index("users_token_permissions_allowed_addresses_parent_id_idx").on(columns._parentID),
		foreignKey({
			columns: [columns["_parentID"]],
			foreignColumns: [users.id],
			name: "users_token_permissions_allowed_addresses_parent_id_fk",
		}).onDelete("cascade"),
	],
)

export const users_token_permissions_allowed_chain_ids = pgTable(
	"users_token_permissions_allowed_chain_ids",
	{
		_order: integer("_order").notNull(),
		_parentID: integer("_parent_id").notNull(),
		id: varchar("id").primaryKey(),
		chainId: numeric("chain_id", { mode: "number" }),
	},
	(columns) => [
		index("users_token_permissions_allowed_chain_ids_order_idx").on(columns._order),
		index("users_token_permissions_allowed_chain_ids_parent_id_idx").on(columns._parentID),
		foreignKey({
			columns: [columns["_parentID"]],
			foreignColumns: [users.id],
			name: "users_token_permissions_allowed_chain_ids_parent_id_fk",
		}).onDelete("cascade"),
	],
)

export const users_campaign_permissions_allowed_campaign_ids = pgTable(
	"users_campaign_permissions_allowed_campaign_ids",
	{
		_order: integer("_order").notNull(),
		_parentID: integer("_parent_id").notNull(),
		id: varchar("id").primaryKey(),
		campaignId: numeric("campaign_id", { mode: "number" }),
	},
	(columns) => [
		index("users_campaign_permissions_allowed_campaign_ids_order_idx").on(columns._order),
		index("users_campaign_permissions_allowed_campaign_ids_parent_id_idx").on(columns._parentID),
		foreignKey({
			columns: [columns["_parentID"]],
			foreignColumns: [users.id],
			name: "users_campaign_permissions_allowed_campaign_ids_parent_id_fk",
		}).onDelete("cascade"),
	],
)

export const users_sessions = pgTable(
	"users_sessions",
	{
		_order: integer("_order").notNull(),
		_parentID: integer("_parent_id").notNull(),
		id: varchar("id").primaryKey(),
		createdAt: timestamp("created_at", { mode: "string", withTimezone: true, precision: 3 }),
		expiresAt: timestamp("expires_at", { mode: "string", withTimezone: true, precision: 3 }).notNull(),
	},
	(columns) => [
		index("users_sessions_order_idx").on(columns._order),
		index("users_sessions_parent_id_idx").on(columns._parentID),
		foreignKey({
			columns: [columns["_parentID"]],
			foreignColumns: [users.id],
			name: "users_sessions_parent_id_fk",
		}).onDelete("cascade"),
	],
)

export const users = pgTable(
	"users",
	{
		id: serial("id").primaryKey(),
		name: varchar("name"),
		role: enum_users_role("role").notNull().default("admin"),
		tokenPermissions_canEditAllTokens: boolean("token_permissions_can_edit_all_tokens").default(true),
		campaignPermissions_canAccessAllCampaigns: boolean("campaign_permissions_can_access_all_campaigns").default(false),
		updatedAt: timestamp("updated_at", { mode: "string", withTimezone: true, precision: 3 }).defaultNow().notNull(),
		createdAt: timestamp("created_at", { mode: "string", withTimezone: true, precision: 3 }).defaultNow().notNull(),
		email: varchar("email").notNull(),
		resetPasswordToken: varchar("reset_password_token"),
		resetPasswordExpiration: timestamp("reset_password_expiration", {
			mode: "string",
			withTimezone: true,
			precision: 3,
		}),
		salt: varchar("salt"),
		hash: varchar("hash"),
		loginAttempts: numeric("login_attempts", { mode: "number" }).default(0),
		lockUntil: timestamp("lock_until", { mode: "string", withTimezone: true, precision: 3 }),
	},
	(columns) => [
		index("users_updated_at_idx").on(columns.updatedAt),
		index("users_created_at_idx").on(columns.createdAt),
		uniqueIndex("users_email_idx").on(columns.email),
	],
)

export const tokens_tags = pgTable(
	"tokens_tags",
	{
		order: integer("order").notNull(),
		parent: varchar("parent_id").notNull(),
		value: enum_tokens_tags("value"),
		id: serial("id").primaryKey(),
	},
	(columns) => [
		index("tokens_tags_order_idx").on(columns.order),
		index("tokens_tags_parent_idx").on(columns.parent),
		foreignKey({
			columns: [columns["parent"]],
			foreignColumns: [tokens.id],
			name: "tokens_tags_parent_fk",
		}).onDelete("cascade"),
	],
)

export const tokens = pgTable(
	"tokens",
	{
		id: varchar("id").primaryKey(),
		chainId: numeric("chain_id", { mode: "number" }).notNull(),
		address: varchar("address").notNull(),
		name: varchar("name").notNull(),
		decimals: numeric("decimals", { mode: "number" }).notNull(),
		symbol: varchar("symbol").notNull(),
		logoUri: varchar("logo_uri"),
		isListed: boolean("is_listed").default(false),
		coingeckoId: varchar("coingecko_id"),
		tokenType: enum_tokens_token_type("token_type").notNull(),
		underlyingAddress: varchar("underlying_address"),
		order: numeric("order", { mode: "number" }).notNull().default(0),
		note: varchar("note"),
		updatedAt: timestamp("updated_at", { mode: "string", withTimezone: true, precision: 3 }).defaultNow().notNull(),
		createdAt: timestamp("created_at", { mode: "string", withTimezone: true, precision: 3 }).defaultNow().notNull(),
	},
	(columns) => [
		index("tokens_updated_at_idx").on(columns.updatedAt),
		index("tokens_created_at_idx").on(columns.createdAt),
	],
)

export const chains_public_r_p_cs = pgTable(
	"chains_public_r_p_cs",
	{
		_order: integer("_order").notNull(),
		_parentID: numeric("_parent_id", { mode: "number" }).notNull(),
		id: varchar("id").primaryKey(),
		url: varchar("url").notNull(),
	},
	(columns) => [
		index("chains_public_r_p_cs_order_idx").on(columns._order),
		index("chains_public_r_p_cs_parent_id_idx").on(columns._parentID),
		foreignKey({
			columns: [columns["_parentID"]],
			foreignColumns: [chains.id],
			name: "chains_public_r_p_cs_parent_id_fk",
		}).onDelete("cascade"),
	],
)

export const chains_trusted_forwarders = pgTable(
	"chains_trusted_forwarders",
	{
		_order: integer("_order").notNull(),
		_parentID: numeric("_parent_id", { mode: "number" }).notNull(),
		id: varchar("id").primaryKey(),
		address: varchar("address").notNull(),
	},
	(columns) => [
		index("chains_trusted_forwarders_order_idx").on(columns._order),
		index("chains_trusted_forwarders_parent_id_idx").on(columns._parentID),
		foreignKey({
			columns: [columns["_parentID"]],
			foreignColumns: [chains.id],
			name: "chains_trusted_forwarders_parent_id_fk",
		}).onDelete("cascade"),
	],
)

export const chains = pgTable(
	"chains",
	{
		id: numeric("id", { mode: "number" }).primaryKey(),
		humanReadableName: varchar("human_readable_name").notNull(),
		canonicalName: varchar("canonical_name").notNull(),
		shortName: varchar("short_name").notNull(),
		uppercaseName: varchar("uppercase_name").notNull(),
		isDeprecated: boolean("is_deprecated").notNull().default(false),
		isTestnet: boolean("is_testnet").notNull().default(false),
		nativeTokenSymbol: varchar("native_token_symbol").notNull(),
		nativeTokenWrapper: varchar("native_token_wrapper"),
		contractsV1_resolver: varchar("contracts_v1_resolver").notNull(),
		contractsV1_host: varchar("contracts_v1_host").notNull(),
		contractsV1_governance: varchar("contracts_v1_governance"),
		contractsV1_cfaV1: varchar("contracts_v1_cfa_v1").notNull(),
		contractsV1_cfaV1Forwarder: varchar("contracts_v1_cfa_v1_forwarder").notNull(),
		contractsV1_idaV1: varchar("contracts_v1_ida_v1").notNull(),
		contractsV1_gdaV1: varchar("contracts_v1_gda_v1"),
		contractsV1_gdaV1Forwarder: varchar("contracts_v1_gda_v1_forwarder"),
		contractsV1_superTokenFactory: varchar("contracts_v1_super_token_factory").notNull(),
		contractsV1_superfluidLoader: varchar("contracts_v1_superfluid_loader").notNull(),
		contractsV1_toga: varchar("contracts_v1_toga"),
		contractsV1_batchLiquidator: varchar("contracts_v1_batch_liquidator"),
		contractsV1_superSpreader: varchar("contracts_v1_super_spreader"),
		contractsV1_existentialNFTCloneFactory: varchar("contracts_v1_existential_n_f_t_clone_factory"),
		contractsV1_macroForwarder: varchar("contracts_v1_macro_forwarder"),
		startBlockV1: numeric("start_block_v1", { mode: "number" }).notNull(),
		logsQueryRange: numeric("logs_query_range", { mode: "number" }).notNull(),
		explorer: varchar("explorer").notNull(),
		subgraphV1_cliName: varchar("subgraph_v1_cli_name"),
		subgraphV1_hostedEndpoint: varchar("subgraph_v1_hosted_endpoint"),
		automations_vestingScheduler: varchar("automations_vesting_scheduler"),
		automations_vestingSchedulerV2: varchar("automations_vesting_scheduler_v2"),
		automations_vestingSchedulerV3: varchar("automations_vesting_scheduler_v3"),
		automations_flowScheduler: varchar("automations_flow_scheduler"),
		automations_manager: varchar("automations_manager"),
		automations_wrapStrategy: varchar("automations_wrap_strategy"),
		automations_subgraphVestingEndpoint: varchar("automations_subgraph_vesting_endpoint"),
		automations_subgraphFlowSchedulerEndpoint: varchar("automations_subgraph_flow_scheduler_endpoint"),
		automations_subgraphAutoWrapEndpoint: varchar("automations_subgraph_auto_wrap_endpoint"),
		coinGeckoId: varchar("coin_gecko_id"),
		updatedAt: timestamp("updated_at", { mode: "string", withTimezone: true, precision: 3 }).defaultNow().notNull(),
		createdAt: timestamp("created_at", { mode: "string", withTimezone: true, precision: 3 }).defaultNow().notNull(),
	},
	(columns) => [
		index("chains_updated_at_idx").on(columns.updatedAt),
		index("chains_created_at_idx").on(columns.createdAt),
	],
)

export const campaigns = pgTable(
	"campaigns",
	{
		id: numeric("id", { mode: "number" }).primaryKey(),
		name: varchar("name").notNull(),
		slug: varchar("slug").notNull(),
		updatedAt: timestamp("updated_at", { mode: "string", withTimezone: true, precision: 3 }).defaultNow().notNull(),
		createdAt: timestamp("created_at", { mode: "string", withTimezone: true, precision: 3 }).defaultNow().notNull(),
	},
	(columns) => [
		uniqueIndex("campaigns_slug_idx").on(columns.slug),
		index("campaigns_updated_at_idx").on(columns.updatedAt),
		index("campaigns_created_at_idx").on(columns.createdAt),
	],
)

export const api_keys = pgTable(
	"api_keys",
	{
		id: serial("id").primaryKey(),
		name: varchar("name").notNull(),
		campaign: numeric("campaign_id", { mode: "number" })
			.notNull()
			.references(() => campaigns.id, {
				onDelete: "set null",
			}),
		rawKey: varchar("raw_key"),
		keyHash: varchar("key_hash"),
		keyPrefix: varchar("key_prefix"),
		status: enum_api_keys_status("status").notNull().default("active"),
		lastUsedAt: timestamp("last_used_at", { mode: "string", withTimezone: true, precision: 3 }),
		updatedAt: timestamp("updated_at", { mode: "string", withTimezone: true, precision: 3 }).defaultNow().notNull(),
		createdAt: timestamp("created_at", { mode: "string", withTimezone: true, precision: 3 }).defaultNow().notNull(),
	},
	(columns) => [
		index("api_keys_campaign_idx").on(columns.campaign),
		uniqueIndex("api_keys_key_hash_idx").on(columns.keyHash),
		index("api_keys_updated_at_idx").on(columns.updatedAt),
		index("api_keys_created_at_idx").on(columns.createdAt),
	],
)

export const push_requests = pgTable(
	"push_requests",
	{
		id: serial("id").primaryKey(),
		campaign: numeric("campaign_id", { mode: "number" })
			.notNull()
			.references(() => campaigns.id, {
				onDelete: "set null",
			}),
		payload: jsonb("payload").notNull(),
		eventCount: numeric("event_count", { mode: "number" }).notNull(),
		status: enum_push_requests_status("status").notNull().default("pending"),
		error: varchar("error"),
		processedAt: timestamp("processed_at", { mode: "string", withTimezone: true, precision: 3 }),
		updatedAt: timestamp("updated_at", { mode: "string", withTimezone: true, precision: 3 }).defaultNow().notNull(),
		createdAt: timestamp("created_at", { mode: "string", withTimezone: true, precision: 3 }).defaultNow().notNull(),
	},
	(columns) => [
		index("push_requests_campaign_idx").on(columns.campaign),
		index("push_requests_status_idx").on(columns.status),
		index("push_requests_updated_at_idx").on(columns.updatedAt),
		index("push_requests_created_at_idx").on(columns.createdAt),
	],
)

export const point_events = pgTable(
	"point_events",
	{
		id: serial("id").primaryKey(),
		campaign: numeric("campaign_id", { mode: "number" })
			.notNull()
			.references(() => campaigns.id, {
				onDelete: "set null",
			}),
		pushRequest: integer("push_request_id").references(() => push_requests.id, {
			onDelete: "set null",
		}),
		eventName: varchar("event_name").notNull(),
		account: varchar("account").notNull(),
		points: numeric("points", { mode: "number" }).notNull(),
		uniqueId: varchar("unique_id"),
		informational: boolean("informational").default(false),
		eventTime: timestamp("event_time", { mode: "string", withTimezone: true, precision: 3 }).notNull(),
		dedupKey: varchar("dedup_key"),
		updatedAt: timestamp("updated_at", { mode: "string", withTimezone: true, precision: 3 }).defaultNow().notNull(),
		createdAt: timestamp("created_at", { mode: "string", withTimezone: true, precision: 3 }).defaultNow().notNull(),
	},
	(columns) => [
		index("point_events_campaign_idx").on(columns.campaign),
		index("point_events_push_request_idx").on(columns.pushRequest),
		index("point_events_event_name_idx").on(columns.eventName),
		index("point_events_account_idx").on(columns.account),
		index("point_events_unique_id_idx").on(columns.uniqueId),
		index("point_events_event_time_idx").on(columns.eventTime),
		uniqueIndex("point_events_dedup_key_idx").on(columns.dedupKey),
		index("point_events_updated_at_idx").on(columns.updatedAt),
		index("point_events_created_at_idx").on(columns.createdAt),
		index("campaign_eventName_idx").on(columns.campaign, columns.eventName),
		index("campaign_eventName_account_idx").on(columns.campaign, columns.eventName, columns.account),
		index("campaign_eventTime_idx").on(columns.campaign, columns.eventTime),
		index("campaign_account_eventTime_idx").on(columns.campaign, columns.account, columns.eventTime),
	],
)

export const point_balances = pgTable(
	"point_balances",
	{
		id: varchar("id").primaryKey(),
		campaign: numeric("campaign_id", { mode: "number" })
			.notNull()
			.references(() => campaigns.id, {
				onDelete: "set null",
			}),
		account: varchar("account").notNull(),
		totalPoints: numeric("total_points", { mode: "number" }).notNull().default(0),
		eventCount: numeric("event_count", { mode: "number" }).notNull().default(0),
		capped: boolean("capped").default(false),
		lastEventAt: timestamp("last_event_at", { mode: "string", withTimezone: true, precision: 3 }),
		updatedAt: timestamp("updated_at", { mode: "string", withTimezone: true, precision: 3 }).defaultNow().notNull(),
		createdAt: timestamp("created_at", { mode: "string", withTimezone: true, precision: 3 }).defaultNow().notNull(),
	},
	(columns) => [
		index("point_balances_campaign_idx").on(columns.campaign),
		index("point_balances_account_idx").on(columns.account),
		index("point_balances_updated_at_idx").on(columns.updatedAt),
		index("point_balances_created_at_idx").on(columns.createdAt),
		index("campaign_account_idx").on(columns.campaign, columns.account),
		index("campaign_totalPoints_idx").on(columns.campaign, columns.totalPoints),
		index("campaign_eventCount_idx").on(columns.campaign, columns.eventCount),
		index("campaign_lastEventAt_idx").on(columns.campaign, columns.lastEventAt),
	],
)

export const payload_kv = pgTable(
	"payload_kv",
	{
		id: serial("id").primaryKey(),
		key: varchar("key").notNull(),
		data: jsonb("data").notNull(),
	},
	(columns) => [uniqueIndex("payload_kv_key_idx").on(columns.key)],
)

export const payload_locked_documents = pgTable(
	"payload_locked_documents",
	{
		id: serial("id").primaryKey(),
		globalSlug: varchar("global_slug"),
		updatedAt: timestamp("updated_at", { mode: "string", withTimezone: true, precision: 3 }).defaultNow().notNull(),
		createdAt: timestamp("created_at", { mode: "string", withTimezone: true, precision: 3 }).defaultNow().notNull(),
	},
	(columns) => [
		index("payload_locked_documents_global_slug_idx").on(columns.globalSlug),
		index("payload_locked_documents_updated_at_idx").on(columns.updatedAt),
		index("payload_locked_documents_created_at_idx").on(columns.createdAt),
	],
)

export const payload_locked_documents_rels = pgTable(
	"payload_locked_documents_rels",
	{
		id: serial("id").primaryKey(),
		order: integer("order"),
		parent: integer("parent_id").notNull(),
		path: varchar("path").notNull(),
		usersID: integer("users_id"),
		tokensID: varchar("tokens_id"),
		chainsID: numeric("chains_id", { mode: "number" }),
		campaignsID: numeric("campaigns_id", { mode: "number" }),
		"api-keysID": integer("api_keys_id"),
		"push-requestsID": integer("push_requests_id"),
		"point-eventsID": integer("point_events_id"),
		"point-balancesID": varchar("point_balances_id"),
	},
	(columns) => [
		index("payload_locked_documents_rels_order_idx").on(columns.order),
		index("payload_locked_documents_rels_parent_idx").on(columns.parent),
		index("payload_locked_documents_rels_path_idx").on(columns.path),
		index("payload_locked_documents_rels_users_id_idx").on(columns.usersID),
		index("payload_locked_documents_rels_tokens_id_idx").on(columns.tokensID),
		index("payload_locked_documents_rels_chains_id_idx").on(columns.chainsID),
		index("payload_locked_documents_rels_campaigns_id_idx").on(columns.campaignsID),
		index("payload_locked_documents_rels_api_keys_id_idx").on(columns["api-keysID"]),
		index("payload_locked_documents_rels_push_requests_id_idx").on(columns["push-requestsID"]),
		index("payload_locked_documents_rels_point_events_id_idx").on(columns["point-eventsID"]),
		index("payload_locked_documents_rels_point_balances_id_idx").on(columns["point-balancesID"]),
		foreignKey({
			columns: [columns["parent"]],
			foreignColumns: [payload_locked_documents.id],
			name: "payload_locked_documents_rels_parent_fk",
		}).onDelete("cascade"),
		foreignKey({
			columns: [columns["usersID"]],
			foreignColumns: [users.id],
			name: "payload_locked_documents_rels_users_fk",
		}).onDelete("cascade"),
		foreignKey({
			columns: [columns["tokensID"]],
			foreignColumns: [tokens.id],
			name: "payload_locked_documents_rels_tokens_fk",
		}).onDelete("cascade"),
		foreignKey({
			columns: [columns["chainsID"]],
			foreignColumns: [chains.id],
			name: "payload_locked_documents_rels_chains_fk",
		}).onDelete("cascade"),
		foreignKey({
			columns: [columns["campaignsID"]],
			foreignColumns: [campaigns.id],
			name: "payload_locked_documents_rels_campaigns_fk",
		}).onDelete("cascade"),
		foreignKey({
			columns: [columns["api-keysID"]],
			foreignColumns: [api_keys.id],
			name: "payload_locked_documents_rels_api_keys_fk",
		}).onDelete("cascade"),
		foreignKey({
			columns: [columns["push-requestsID"]],
			foreignColumns: [push_requests.id],
			name: "payload_locked_documents_rels_push_requests_fk",
		}).onDelete("cascade"),
		foreignKey({
			columns: [columns["point-eventsID"]],
			foreignColumns: [point_events.id],
			name: "payload_locked_documents_rels_point_events_fk",
		}).onDelete("cascade"),
		foreignKey({
			columns: [columns["point-balancesID"]],
			foreignColumns: [point_balances.id],
			name: "payload_locked_documents_rels_point_balances_fk",
		}).onDelete("cascade"),
	],
)

export const payload_preferences = pgTable(
	"payload_preferences",
	{
		id: serial("id").primaryKey(),
		key: varchar("key"),
		value: jsonb("value"),
		updatedAt: timestamp("updated_at", { mode: "string", withTimezone: true, precision: 3 }).defaultNow().notNull(),
		createdAt: timestamp("created_at", { mode: "string", withTimezone: true, precision: 3 }).defaultNow().notNull(),
	},
	(columns) => [
		index("payload_preferences_key_idx").on(columns.key),
		index("payload_preferences_updated_at_idx").on(columns.updatedAt),
		index("payload_preferences_created_at_idx").on(columns.createdAt),
	],
)

export const payload_preferences_rels = pgTable(
	"payload_preferences_rels",
	{
		id: serial("id").primaryKey(),
		order: integer("order"),
		parent: integer("parent_id").notNull(),
		path: varchar("path").notNull(),
		usersID: integer("users_id"),
	},
	(columns) => [
		index("payload_preferences_rels_order_idx").on(columns.order),
		index("payload_preferences_rels_parent_idx").on(columns.parent),
		index("payload_preferences_rels_path_idx").on(columns.path),
		index("payload_preferences_rels_users_id_idx").on(columns.usersID),
		foreignKey({
			columns: [columns["parent"]],
			foreignColumns: [payload_preferences.id],
			name: "payload_preferences_rels_parent_fk",
		}).onDelete("cascade"),
		foreignKey({
			columns: [columns["usersID"]],
			foreignColumns: [users.id],
			name: "payload_preferences_rels_users_fk",
		}).onDelete("cascade"),
	],
)

export const payload_migrations = pgTable(
	"payload_migrations",
	{
		id: serial("id").primaryKey(),
		name: varchar("name"),
		batch: numeric("batch", { mode: "number" }),
		updatedAt: timestamp("updated_at", { mode: "string", withTimezone: true, precision: 3 }).defaultNow().notNull(),
		createdAt: timestamp("created_at", { mode: "string", withTimezone: true, precision: 3 }).defaultNow().notNull(),
	},
	(columns) => [
		index("payload_migrations_updated_at_idx").on(columns.updatedAt),
		index("payload_migrations_created_at_idx").on(columns.createdAt),
	],
)

export const relations_users_token_permissions_allowed_tags = relations(
	users_token_permissions_allowed_tags,
	({ one }) => ({
		_parentID: one(users, {
			fields: [users_token_permissions_allowed_tags._parentID],
			references: [users.id],
			relationName: "tokenPermissions_allowedTags",
		}),
	}),
)
export const relations_users_token_permissions_allowed_addresses = relations(
	users_token_permissions_allowed_addresses,
	({ one }) => ({
		_parentID: one(users, {
			fields: [users_token_permissions_allowed_addresses._parentID],
			references: [users.id],
			relationName: "tokenPermissions_allowedAddresses",
		}),
	}),
)
export const relations_users_token_permissions_allowed_chain_ids = relations(
	users_token_permissions_allowed_chain_ids,
	({ one }) => ({
		_parentID: one(users, {
			fields: [users_token_permissions_allowed_chain_ids._parentID],
			references: [users.id],
			relationName: "tokenPermissions_allowedChainIds",
		}),
	}),
)
export const relations_users_campaign_permissions_allowed_campaign_ids = relations(
	users_campaign_permissions_allowed_campaign_ids,
	({ one }) => ({
		_parentID: one(users, {
			fields: [users_campaign_permissions_allowed_campaign_ids._parentID],
			references: [users.id],
			relationName: "campaignPermissions_allowedCampaignIds",
		}),
	}),
)
export const relations_users_sessions = relations(users_sessions, ({ one }) => ({
	_parentID: one(users, {
		fields: [users_sessions._parentID],
		references: [users.id],
		relationName: "sessions",
	}),
}))
export const relations_users = relations(users, ({ many }) => ({
	tokenPermissions_allowedTags: many(users_token_permissions_allowed_tags, {
		relationName: "tokenPermissions_allowedTags",
	}),
	tokenPermissions_allowedAddresses: many(users_token_permissions_allowed_addresses, {
		relationName: "tokenPermissions_allowedAddresses",
	}),
	tokenPermissions_allowedChainIds: many(users_token_permissions_allowed_chain_ids, {
		relationName: "tokenPermissions_allowedChainIds",
	}),
	campaignPermissions_allowedCampaignIds: many(users_campaign_permissions_allowed_campaign_ids, {
		relationName: "campaignPermissions_allowedCampaignIds",
	}),
	sessions: many(users_sessions, {
		relationName: "sessions",
	}),
}))
export const relations_tokens_tags = relations(tokens_tags, ({ one }) => ({
	parent: one(tokens, {
		fields: [tokens_tags.parent],
		references: [tokens.id],
		relationName: "tags",
	}),
}))
export const relations_tokens = relations(tokens, ({ many }) => ({
	tags: many(tokens_tags, {
		relationName: "tags",
	}),
}))
export const relations_chains_public_r_p_cs = relations(chains_public_r_p_cs, ({ one }) => ({
	_parentID: one(chains, {
		fields: [chains_public_r_p_cs._parentID],
		references: [chains.id],
		relationName: "publicRPCs",
	}),
}))
export const relations_chains_trusted_forwarders = relations(chains_trusted_forwarders, ({ one }) => ({
	_parentID: one(chains, {
		fields: [chains_trusted_forwarders._parentID],
		references: [chains.id],
		relationName: "trustedForwarders",
	}),
}))
export const relations_chains = relations(chains, ({ many }) => ({
	publicRPCs: many(chains_public_r_p_cs, {
		relationName: "publicRPCs",
	}),
	trustedForwarders: many(chains_trusted_forwarders, {
		relationName: "trustedForwarders",
	}),
}))
export const relations_campaigns = relations(campaigns, () => ({}))
export const relations_api_keys = relations(api_keys, ({ one }) => ({
	campaign: one(campaigns, {
		fields: [api_keys.campaign],
		references: [campaigns.id],
		relationName: "campaign",
	}),
}))
export const relations_push_requests = relations(push_requests, ({ one }) => ({
	campaign: one(campaigns, {
		fields: [push_requests.campaign],
		references: [campaigns.id],
		relationName: "campaign",
	}),
}))
export const relations_point_events = relations(point_events, ({ one }) => ({
	campaign: one(campaigns, {
		fields: [point_events.campaign],
		references: [campaigns.id],
		relationName: "campaign",
	}),
	pushRequest: one(push_requests, {
		fields: [point_events.pushRequest],
		references: [push_requests.id],
		relationName: "pushRequest",
	}),
}))
export const relations_point_balances = relations(point_balances, ({ one }) => ({
	campaign: one(campaigns, {
		fields: [point_balances.campaign],
		references: [campaigns.id],
		relationName: "campaign",
	}),
}))
export const relations_payload_kv = relations(payload_kv, () => ({}))
export const relations_payload_locked_documents_rels = relations(payload_locked_documents_rels, ({ one }) => ({
	parent: one(payload_locked_documents, {
		fields: [payload_locked_documents_rels.parent],
		references: [payload_locked_documents.id],
		relationName: "_rels",
	}),
	usersID: one(users, {
		fields: [payload_locked_documents_rels.usersID],
		references: [users.id],
		relationName: "users",
	}),
	tokensID: one(tokens, {
		fields: [payload_locked_documents_rels.tokensID],
		references: [tokens.id],
		relationName: "tokens",
	}),
	chainsID: one(chains, {
		fields: [payload_locked_documents_rels.chainsID],
		references: [chains.id],
		relationName: "chains",
	}),
	campaignsID: one(campaigns, {
		fields: [payload_locked_documents_rels.campaignsID],
		references: [campaigns.id],
		relationName: "campaigns",
	}),
	"api-keysID": one(api_keys, {
		fields: [payload_locked_documents_rels["api-keysID"]],
		references: [api_keys.id],
		relationName: "api-keys",
	}),
	"push-requestsID": one(push_requests, {
		fields: [payload_locked_documents_rels["push-requestsID"]],
		references: [push_requests.id],
		relationName: "push-requests",
	}),
	"point-eventsID": one(point_events, {
		fields: [payload_locked_documents_rels["point-eventsID"]],
		references: [point_events.id],
		relationName: "point-events",
	}),
	"point-balancesID": one(point_balances, {
		fields: [payload_locked_documents_rels["point-balancesID"]],
		references: [point_balances.id],
		relationName: "point-balances",
	}),
}))
export const relations_payload_locked_documents = relations(payload_locked_documents, ({ many }) => ({
	_rels: many(payload_locked_documents_rels, {
		relationName: "_rels",
	}),
}))
export const relations_payload_preferences_rels = relations(payload_preferences_rels, ({ one }) => ({
	parent: one(payload_preferences, {
		fields: [payload_preferences_rels.parent],
		references: [payload_preferences.id],
		relationName: "_rels",
	}),
	usersID: one(users, {
		fields: [payload_preferences_rels.usersID],
		references: [users.id],
		relationName: "users",
	}),
}))
export const relations_payload_preferences = relations(payload_preferences, ({ many }) => ({
	_rels: many(payload_preferences_rels, {
		relationName: "_rels",
	}),
}))
export const relations_payload_migrations = relations(payload_migrations, () => ({}))

type DatabaseSchema = {
	enum_users_role: typeof enum_users_role
	enum_tokens_tags: typeof enum_tokens_tags
	enum_tokens_token_type: typeof enum_tokens_token_type
	enum_api_keys_status: typeof enum_api_keys_status
	enum_push_requests_status: typeof enum_push_requests_status
	users_token_permissions_allowed_tags: typeof users_token_permissions_allowed_tags
	users_token_permissions_allowed_addresses: typeof users_token_permissions_allowed_addresses
	users_token_permissions_allowed_chain_ids: typeof users_token_permissions_allowed_chain_ids
	users_campaign_permissions_allowed_campaign_ids: typeof users_campaign_permissions_allowed_campaign_ids
	users_sessions: typeof users_sessions
	users: typeof users
	tokens_tags: typeof tokens_tags
	tokens: typeof tokens
	chains_public_r_p_cs: typeof chains_public_r_p_cs
	chains_trusted_forwarders: typeof chains_trusted_forwarders
	chains: typeof chains
	campaigns: typeof campaigns
	api_keys: typeof api_keys
	push_requests: typeof push_requests
	point_events: typeof point_events
	point_balances: typeof point_balances
	payload_kv: typeof payload_kv
	payload_locked_documents: typeof payload_locked_documents
	payload_locked_documents_rels: typeof payload_locked_documents_rels
	payload_preferences: typeof payload_preferences
	payload_preferences_rels: typeof payload_preferences_rels
	payload_migrations: typeof payload_migrations
	relations_users_token_permissions_allowed_tags: typeof relations_users_token_permissions_allowed_tags
	relations_users_token_permissions_allowed_addresses: typeof relations_users_token_permissions_allowed_addresses
	relations_users_token_permissions_allowed_chain_ids: typeof relations_users_token_permissions_allowed_chain_ids
	relations_users_campaign_permissions_allowed_campaign_ids: typeof relations_users_campaign_permissions_allowed_campaign_ids
	relations_users_sessions: typeof relations_users_sessions
	relations_users: typeof relations_users
	relations_tokens_tags: typeof relations_tokens_tags
	relations_tokens: typeof relations_tokens
	relations_chains_public_r_p_cs: typeof relations_chains_public_r_p_cs
	relations_chains_trusted_forwarders: typeof relations_chains_trusted_forwarders
	relations_chains: typeof relations_chains
	relations_campaigns: typeof relations_campaigns
	relations_api_keys: typeof relations_api_keys
	relations_push_requests: typeof relations_push_requests
	relations_point_events: typeof relations_point_events
	relations_point_balances: typeof relations_point_balances
	relations_payload_kv: typeof relations_payload_kv
	relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels
	relations_payload_locked_documents: typeof relations_payload_locked_documents
	relations_payload_preferences_rels: typeof relations_payload_preferences_rels
	relations_payload_preferences: typeof relations_payload_preferences
	relations_payload_migrations: typeof relations_payload_migrations
}

declare module "@payloadcms/db-vercel-postgres" {
	export interface GeneratedDatabaseSchema {
		schema: DatabaseSchema
	}
}
