name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.6.2

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Check Code Format
        run: pnpm check:ci

      - name: Build All Packages
        run: pnpm build
        env:
          DATABASE_URI: file:./superfluid-cms.db
          PAYLOAD_SECRET: 66fa5bb4549644545ae3f069 # Not production secret

      - name: Run Tests
        run: pnpm test --filter=@sfpro/sdk

      - name: Type Check
        run: pnpm typecheck --filter=@sfpro/sdk

      - name: Validate SDK Package
        run: pnpm --filter=@sfpro/sdk check:package